title: Open Project Night Seattle
description: "Learn, Make, & Share!"
permalink: /posts/:title
baseurl: ''
exclude: [node_modules, tmp, assets/deps.css]

collections:
  events:
    output: true
    permalink: /events/:path/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
